### ISSUE TITLE
A successful upgrade results mis-formatted congratulations as failed error message

### ISSUE THREAD

**Issue by jeffnm** [wc-library/Coral#17]
Image:

![screen shot 2016-11-02 at 4 32 36 pm](https://cloud.githubusercontent.com/assets/651304/19948321/f5cf7afe-a119-11e6-96cb-9b069928102b.png)

Text:

string(9) "resources"
{"show_completion":true,"completion_title":"Congratulations","redirection_message":"Redirecting Home: ","completion_message":"Upgrade has been successfully completed.","completion":100,"completed_tests":["Meets system requirements","Config File Access","Authentication Module","Licensing Module","Management Module","Organizations Module","Reports Module","Database Access","Resources Module","Usage Module"]}

**Comment by jcuenod** [comment]
Yes, my bad - I've definitely fixed this.
I was just an idiot that "string(9)" is because I was `var_dump`ing to check that sql files were being skipped once they'd been processed but it breaks the json output (I've removed it from `install/providers/db_tools.php` in https://github.com/jcuenod/Coral/commit/0f65dc0287725437a6b61232ac00d8952008c7b2)

**Comment by jeffnm** [comment]
Not a problem var dumping during dev is to be encouraged. :) Thanks for removing it. I didn't get to test it before I left, but if I have some spare time this week I'll give it another go.
