### ISSUE TITLE
Merging jcuenod/Coral:upgrades into wc-library

### ISSUE THREAD

**Issue by jcuenod** [wc-library/Coral#18]
For some reason I'm having a lot of trouble putting together a pull request to do this. Whatever I do I'm ending up with a request that contains changes that should already have been merged in (the last merge happened about 20 days ago so anything before early October should not be showing up but it is).

**Comment by jeffnm** [comment]
Hmm. Which branch are you targeting?

**Comment by jcuenod** [comment]
upgrades (on both wc-library and jcuenod)

**Comment by jeffnm** [comment]
Yeah, I'm getting that too. It looks like I squashed the commits in the last merge  (#10), and I'm guessing that's why these commits are considered new. I guess I shouldn't have done that.  

Your version is what we should have, so I could delete wc-library's upgrade branch, recreate it, and then do a fresh pull request with all changes. Do you have any objections?

**Comment by jcuenod** [comment]
No, that's fine with me.

I was trying to figure out whether any changes had been made on the wc-library
branch that were being buried in the massive list. I would be surprised (who
is testing the upgrades branch apart from you) - but it's not impossible.

**Comment by jcuenod** [comment]
I should also say, my git-fu is not great so this could totally be something I messed up and just don't know about...

**Comment by jeffnm** [comment]
I didn't make any changes on that branch. I sent the changes I'd made to
you directly or explained them in an issue, precisely because I thought
chances were we'd end up with conflicts if I did them myself on that
branch. And my git abilities are also a little shaky at times. I think I'll
avoid squashing commits in the future, unless I'm doing them on my own
branch before passing them on.

**Comment by jeffnm** [comment]
It looks like squashed commits make sense when merging a finished work in
progress branch (e.g. a new feature that is complete and needs to be merged
into the master branch). Since my upgrades branch is intended to be a WIP
branch like yours, maintaining the commits at this time is better.

**Comment by jcuenod** [comment]
Fair enough

**Comment by jeffnm** [comment]
I did make and merge the pull request, so I'm closing this issue.
